#ifndef VERYSIMPLE_VM_INSTRUCTION_SET_H
#define VERYSIMPLE_VM_INSTRUCTION_SET_H

enum {
    VERYSIMPLE_VM_HALT,
    VERYSIMPLE_VM_ICONST,
    VERYSIMPLE_VM_IADD,
    VERYSIMPLE_VM_ISUB,
    VERYSIMPLE_VM_IMUL,
    VERYSIMPLE_VM_LT,
    VERYSIMPLE_VM_GT,
    VERYSIMPLE_VM_EQ,
    VERYSIMPLE_VM_NEQ,
    VERYSIMPLE_VM_BRT,
    VERYSIMPLE_VM_BRF,
    VERYSIMPLE_VM_CALL,
    VERYSIMPLE_VM_RET,
    VERYSIMPLE_VM_LOAD,
    VERYSIMPLE_VM_PRINT,
};

#endif //VERYSIMPLE_VM_INSTRUCTION_SET_H
